name: hitachi
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+29

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  page_transition: ^2.0.9
  bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  dio: ^5.1.1
  syncfusion_flutter_datagrid: ^21.1.41
  flutter_easyloading: ^3.0.5
  sqflite: ^2.2.8
  path_provider: ^2.0.14
  dotted_line: ^3.1.0
  dropdown_button2: ^2.1.0
  intl: ^0.18.1
  flutter_spinkit: ^5.2.0
  package_info_plus: ^4.0.1
  shared_preferences: ^2.1.1
  rflutter_alert: ^2.0.7
  connectivity_plus: ^4.0.2
  bot_toast: ^4.1.1
  get: ^4.7.2
  font_awesome_flutter: ^10.5.0
  win32: ^5.10.0 # Downgrade win32 to a compatible version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logoApp/Abb.png
